### PR TITLE
feature(auth): Support jwt auth

### PR DESCRIPTION
**Pull request by KannarFr**

### CODE REVIEW

**Review by leshow — APPROVED** [review]
I think we can nest an `Authentication` struct and use `#[serde(flatten)]` but I'll add that in later. I've been a bit slow on this b/c I've been sick since last week. We're also waiting on the `pulsar` changes to get merged anyway.

**Comment by KannarFr** [comment]
Oh, hope you're doing well now! No worries :). Which pulsar changes need to get merged? @leshow

**Comment by leshow** [comment]
This change to `vector` relies on changes in `pulsar` also getting merged (the generic executor stuff), you may have noticed the `pulsar` crate in this branch's `Cargo.toml` is just pointing to my fork. `pulsar-rs` needs to cut a release and all that before the changes can go in.

edit: I'm going to make this auth token optional too

**Comment by KannarFr** [comment]
Yup, but can you link the related PR to pulsar-rs? :)

**Comment by leshow** [comment]
https://github.com/wyyerd/pulsar-rs/pull/57

**Pull request merged**
